### ISSUE TITLE
Version tag?

### ISSUE THREAD

**Issue by TiGR** [jguyomard/silex-capsule-eloquent#2]
Could you, please, add version tag (actually anything, even `0.0.0` works) and then make sure it is updated in packagist also? This helps in speeding up composer installs as it starts caching package and no longer connect github on every install or update.

**Comment by jguyomard** [comment]
Hi Igor,
Thank you for this issue ; I've just added a v2.0.0 version tag in github+packagist.
Please tell me if everything is OK

**Comment by TiGR** [comment]
Yes, thank you. It is cacheable now:

```
$ composer install
...
  - Installing jguyomard/silex-capsule-eloquent (v2.0.0)
    Loading from cache
...
```
