### ISSUE TITLE
can you make new version with commit af80269 and update in packagist also.

### ISSUE THREAD

**Issue by Rakitin** [jguyomard/silex-capsule-eloquent#4]
can you make new version with commit af80269 and update in packagist also. i'd like to update my project

**Comment by jguyomard** [comment]
i already published version v2.0.1 after your PR: https://packagist.org/packages/jguyomard/silex-capsule-eloquent#v2.0.1
Is everythink okay?

**Comment by Rakitin** [comment]
good. now work query listen:

$app->extend('capsule', function ($capsule, $app) {
    $capsule->connection()->listen(function ($query) {
        dump($query->sql);
        dump($query->bindings);
        dump($query->time);
    });

```
return $capsule;
```

});

and I can logging query!!!  :)
