### ISSUE TITLE
Use with Symfony console

### ISSUE THREAD

**Issue by matracine** [jguyomard/silex-capsule-eloquent#5]
Hello,

I'm trying to use CapsuleServiceProvider in a Symfony 3.1 console project.
I managed to have it working by replacing all "Silex\Application $app" in closures' paramters with "Pimple\Container $app" in the register method.

I have to boot the capsule provider manualy by calling $app['capsule'].

It works perfectly for me. Is it possible to merge this in your repo ?
Going to make a pull request.

**Comment by jguyomard** [comment]
Hello,

Yes, it's a good idea, i will merge your PR this morning.
Thank you

**Comment by jguyomard** [comment]
#6 merged, and v2.0.2 published on packagist
